references:
  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: /tmp/simuimmo
      paths:
        - build

  restore-workspace: &restore-workspace
    attach_workspace:
      at: /tmp/simuimmo

  defaults: &defaults
    working_directory: /tmp/simuimmo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --pure-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn lint

      - run: yarn build:prod

      - *persist-workspace

  deploy-s3:
    <<: *defaults
    docker:
      - image: circleci/python:2.7-jessie      
    steps:
      - *restore-workspace
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          # deploy on S3
          name: Deploy Master on S3
          command: |
            echo $S3_BUCKET
            aws s3 cp build $S3_BUCKET --recursive --acl public-read --region eu-west-3

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - build
      - deploy-s3:
          requires:
            - build
          filters:
            branches:
              only: master
