export const SET_INTEREST_RATE = 'SET_INTEREST_RATE';
export const SET_INSURANCE_RATE = 'SET_INSURANCE_RATE';
export const SET_DURATION = 'SET_DURATION';
export const SET_CAPITAL = 'SET_CAPITAL';
export const SET_FORM_VALUE = 'SET_FORM_VALUE';
